### ISSUE TITLE
catching errors requires await even when calling synchronous functions

### ISSUE THREAD

**Issue by parthnaik** [sindresorhus/emittery#66] opened 2020-10-28 08:37 UTC
```js
const Emittery = require('emittery')
const eventEmitter = new Emittery()

async function asyncFunction() {
    throw new Error('Async function error')
}

eventEmitter.on('callAsyncFunction', asyncFunction)

const runAsyncFunction = async() => {
    try {
        await eventEmitter.emit('callAsyncFunction')
    } catch(e) {
        console.log(e)
    }
}

runAsyncFunction() // Works as expected and prints 'Async function error'.


function syncFunction() {
    throw new Error('Sync function error')
}

eventEmitter.on('callSyncFunction', syncFunction) 

try {
    eventEmitter.emit('callSyncFunction') // Needs await if I want to catch the error even though it is calling a sync function to work as expected.
} catch(e) {
    console.log(e)
}
// Unhandled Promise Rejection. Requires await before eventEmitter.emit('callSyncFunction') even though calling sync function to allow it to catch the error.
```
Right now I am using the in-built node eventEmitter for synchronous functions and this one for async functions. If this is fixed, I can simply use this emitter and not use the in-built one at all.

**Comment by sindresorhus** [comment] 2020-12-28 17:25
That's by design. Emittery is fully async even if the listener is not an async function.

**Comment by sindresorhus** [comment] 2020-12-28 17:25
Duplicate of https://github.com/sindresorhus/emittery/issues/48

**Closed by sindresorhus** 2020-12-28 17:25 UTC
