### ISSUE TITLE
`export = Emittery` might not be correct?

### ISSUE THREAD

**Issue by davidmurdoch** [sindresorhus/emittery#92] opened 2021-12-17 18:03 UTC
https://github.com/sindresorhus/emittery/blob/de3d78d67f9e099beff6384d1a59213c801562b6/index.d.ts#L597

Microsoft's "API Extractor" (a bit like webpack, but for TypeScript types) doesn't understand this syntax and errors because of it. See: https://github.com/microsoft/rushstack/issues/2220 This is likely an API Extractor bug, and this issue here could be closed, but I thought I'd open it in case a "fix" was warranted anyway.

I think this "fixes" it:

```
export default Emittery
```

But I don't know enough about `.d.ts` files to understand the full ramifications of making this change.

**Comment by sindresorhus** [comment] 2021-12-17 19:24
Not a bug with this package.

This package will move to ESM when TS 4.6 is out, so it will be fixed early next year:

**Closed** 2021-12-17 19:30 UTC
